In [2]:
import numpy as np

print(np.__version__)

1.24.4


# Array creation

In [3]:
# create a numpy with size 10, filled with zero
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# create a numpy array with values from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# Create a numpy matrix of 2*2 integers, filled with ones.
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [8]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Given the X numpy array, 
# # create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(4, dtype=int)
np.ones_like(X)

array([1, 1, 1, 1])

In [12]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
X = np.array([[1,2,3], [4,5,6]], dtype=int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
# Create a numpy matrix of 4*4 integers, filled with fives
np.ones((4,4),dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [14]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[2,3], [6,2]], dtype=int)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [17]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
# Create a numpy array, filled with 3 random integer values between 1 and 10
np.random.randint(1,10, size=3)

array([6, 5, 2])

In [25]:
# Create a 3*3*3 numpy matrix, filled with random float values.
np.random.randn(3,3,3)

array([[[ 0.91440963, -0.80388716, -1.16914106],
        [ 0.25640806, -0.31363405,  1.39228046],
        [ 0.31949255, -0.26879808, -0.02379246]],

       [[-0.07120218, -0.97678403, -0.5906645 ],
        [ 0.10917304,  0.08290322,  1.44756218],
        [-0.43643139,  0.2927595 ,  0.3228378 ]],

       [[-1.68876736, -0.37349529,  0.68099339],
        [ 0.56663295,  1.3554761 ,  0.66977688],
        [-0.35929149,  0.39493591,  0.94112155]]])

In [28]:
# Given the X python list convert it to an Y numpy array
X = [1, 2, 3]
print(X, type(X))
Y= np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [53]:
# Given the X numpy array, make a copy and store it on Y.
X = np.array([5,2,3], dtype=int)
print(X, id(X))
# Y= np.copy(X)

Y=X
print(Y, id(Y))

X =np.array([5,5,5], dtype=int)
print(X, id(X))
print(Y, id(Y))

[5 2 3] 2141121709808
[5 2 3] 2141121709808
[5 5 5] 2141117840624
[5 2 3] 2141121709808


In [54]:
X = np.array([5,2,3], dtype=int)
print(X, id(X))
Y= np.copy(X)

print(Y, id(Y))

X =np.array([5,5,5], dtype=int)
print(X, id(X))
print(Y, id(Y))

[5 2 3] 2141121543984
[5 2 3] 2141117840624
[5 5 5] 2141120935472
[5 2 3] 2141117840624


In [55]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# Create a numpy array with the odd numbers between 1 to 10

In [60]:
# Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [63]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
np.arange(9).reshape([3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
# Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))
print(Z.size)
print(Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

100
8
800 bytes


# Array indexation

In [68]:
# Given the X numpy array, show it's first element
X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [69]:
# Given the X numpy array, show it's last element
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [70]:
# Given the X numpy array, show all middle elements
X = np.array(['A','B','C','D','E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [71]:
# Given the X numpy array, show the elements in reverse position
X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [73]:
# Given the X numpy array, show the elements in an odd position
X = np.array(['A','B','C','D','E'])
X[0::2]

array(['A', 'C', 'E'], dtype='<U1')

In [74]:
# Given the X numpy matrix, show the first row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]


array([1, 2, 3, 4])

In [75]:
# # Given the X numpy matrix, show the last row elements
X[-1]

array([13, 14, 15, 16])

In [76]:
# Given the X numpy matrix, show the first element on first row
X[0,0]

1

In [77]:
# Given the X numpy matrix, show the last element on last row
X[-1,-1]

16

In [78]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [81]:
#Given the X numpy matrix, show the middle row elements
X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

In [82]:
# Given the X numpy matrix, show the first two elements on the first two rows
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [86]:
# Given the X numpy matrix, show the last two elements on the last two rows
X[2:,2:]

array([[11, 12],
       [15, 16]])

# Array manipulation

In [89]:
# Convert the given integer numpy array to float
X = [-5, -3, 0, 10, 40]
X =np.array(X,dtype=float)

print(X,type(X))

[-5. -3.  0. 10. 40.] <class 'numpy.ndarray'>


In [108]:
# Reverse the given numpy array (first element becomes last)
X = [-5, 13, 0, 10, 40]

X =X[::-1]

print(X)


[40, 10, 0, 13, -5]


In [109]:
X.sort()
print(X)

[-5, 0, 10, 13, 40]


In [111]:
# Given the X numpy array, set the fifth element equal to 1
X = np.zeros(10)
X[4] = 1

print(X)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [116]:
# Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


X[-1::] = 1

print(X)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [119]:
# Given the X numpy matrix, add 5 to every element
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X= X + 5

print(X)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# Boolean Array

In [123]:
# Given the X numpy array, make a mask showing negative elements

X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X<0
print(mask)

[ True False False  True False False False False  True False]


In [124]:
X_neg = X[mask]
print(X_neg)

[-1 -4 -9]


In [125]:
# Given the X numpy array, get numbers higher than 5
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X[X>5]

array([ 6, 10])

In [126]:
# Given the X numpy array, get numbers higher than the elements mean
X[X>X.mean()]

array([ 2,  5,  6, 10])

# logic function

In [128]:
# Given the X numpy array, return True if none of its elements is zero
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

In [129]:
# Given the X numpy array, return True if any of its elements is zero
X.any()

True

# Statistics

In [130]:
# Given the X numpy array, show the sum of its elements
X.sum()

9

In [132]:
# Given the X numpy array, show the mean value of its elements

X.mean()

0.9

In [135]:
# Given the X numpy matrix, show the sum of its columns
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

array([28, 32, 36, 40])

In [139]:
# Given the X numpy matrix, show the mean value of its rows
X.sum(axis=1)

array([10, 26, 42, 58])

In [140]:
#Given the X numpy matrix, show the mean value of its rows
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [141]:
# Given the X numpy array, show the max value of its elements
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.max()

10